language: go
go:
- 1.4
env:
  global:
  - GOPATH="$HOME/gopath"
before_script:
- mkdir -p $HOME/gopath/src/github.com/zmap
- ln -s $TRAVIS_BUILD_DIR $HOME/gopath/src/github.com/zmap/ || true
- go get gopkg.in/check.v1
- go get github.com/dadrian/rc2
script:
- go test -v ./...
notifications:
  email:
  - zmap-devel@umich.edu
  slack:
    secure: C9nvJpSXSBuqfyv7z+vt+d0CQ4ZC5JklQj9iY9g1jpObDeBG13/THKxINTAAkKIjrgZHkeSVRjOSAE+pz6XbGKFBoFwsKqx9kc4rM7rZumlRalXgyTMc2nInWVcCwlQBGHTAmqPudXR4zMD8xRM9iNxpzOIb2cjOkPRAHw1cCXY=
